/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TabsRouteRouteImport } from './routes/_tabs/route'
import { Route as TabsExploreRouteImport } from './routes/_tabs/explore'
import { Route as TabsHistoryRouteImport } from './routes/_tabs/history'
import { Route as MediaSlugIndexRouteImport } from './routes/media/$slug/index'
import { Route as MediaSlugChapterSlugIndexRouteImport } from './routes/media/$slug/$chapterSlug/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRouteRoute = TabsRouteRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsExploreRoute = TabsExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => TabsRouteRoute,
} as any)
const TabsHistoryRoute = TabsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => TabsRouteRoute,
} as any)
const MediaSlugIndexRoute = MediaSlugIndexRouteImport.update({
  id: '/media/$slug/',
  path: '/media/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSlugChapterSlugIndexRoute =
  MediaSlugChapterSlugIndexRouteImport.update({
    id: '/media/$slug/$chapterSlug/',
    path: '/media/$slug/$chapterSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof TabsExploreRoute
  '/history': typeof TabsHistoryRoute
  '/media/$slug/': typeof MediaSlugIndexRoute
  '/media/$slug/$chapterSlug/': typeof MediaSlugChapterSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof TabsExploreRoute
  '/history': typeof TabsHistoryRoute
  '/media/$slug': typeof MediaSlugIndexRoute
  '/media/$slug/$chapterSlug': typeof MediaSlugChapterSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabs': typeof TabsRouteRouteWithChildren
  '/_tabs/explore': typeof TabsExploreRoute
  '/_tabs/history': typeof TabsHistoryRoute
  '/media/$slug/': typeof MediaSlugIndexRoute
  '/media/$slug/$chapterSlug/': typeof MediaSlugChapterSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/history'
    | '/media/$slug/'
    | '/media/$slug/$chapterSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/explore' | '/history' | '/media/$slug' | '/media/$slug/$chapterSlug'
  id:
    | '__root__'
    | '/'
    | '/_tabs'
    | '/_tabs/explore'
    | '/_tabs/history'
    | '/media/$slug/'
    | '/media/$slug/$chapterSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRouteRoute: typeof TabsRouteRouteWithChildren
  MediaSlugIndexRoute: typeof MediaSlugIndexRoute
  MediaSlugChapterSlugIndexRoute: typeof MediaSlugChapterSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/explore': {
      id: '/_tabs/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof TabsExploreRouteImport
      parentRoute: typeof TabsRouteRoute
    }
    '/_tabs/history': {
      id: '/_tabs/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof TabsHistoryRouteImport
      parentRoute: typeof TabsRouteRoute
    }
    '/media/$slug/': {
      id: '/media/$slug/'
      path: '/media/$slug'
      fullPath: '/media/$slug/'
      preLoaderRoute: typeof MediaSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$slug/$chapterSlug/': {
      id: '/media/$slug/$chapterSlug/'
      path: '/media/$slug/$chapterSlug'
      fullPath: '/media/$slug/$chapterSlug/'
      preLoaderRoute: typeof MediaSlugChapterSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TabsRouteRouteChildren {
  TabsExploreRoute: typeof TabsExploreRoute
  TabsHistoryRoute: typeof TabsHistoryRoute
}

const TabsRouteRouteChildren: TabsRouteRouteChildren = {
  TabsExploreRoute: TabsExploreRoute,
  TabsHistoryRoute: TabsHistoryRoute,
}

const TabsRouteRouteWithChildren = TabsRouteRoute._addFileChildren(
  TabsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRouteRoute: TabsRouteRouteWithChildren,
  MediaSlugIndexRoute: MediaSlugIndexRoute,
  MediaSlugChapterSlugIndexRoute: MediaSlugChapterSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
