/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TabsRouteRouteImport } from './routes/_tabs/route'
import { Route as TabsExploreRouteImport } from './routes/_tabs/explore'
import { Route as TabsHistoryRouteImport } from './routes/_tabs/history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRouteRoute = TabsRouteRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsExploreRoute = TabsExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => TabsRouteRoute,
} as any)
const TabsHistoryRoute = TabsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => TabsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof TabsExploreRoute
  '/history': typeof TabsHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof TabsExploreRoute
  '/history': typeof TabsHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabs': typeof TabsRouteRouteWithChildren
  '/_tabs/explore': typeof TabsExploreRoute
  '/_tabs/history': typeof TabsHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/explore' | '/history'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explore' | '/history'
  id: '__root__' | '/' | '/_tabs' | '/_tabs/explore' | '/_tabs/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRouteRoute: typeof TabsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/explore': {
      id: '/_tabs/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof TabsExploreRouteImport
      parentRoute: typeof TabsRouteRoute
    }
    '/_tabs/history': {
      id: '/_tabs/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof TabsHistoryRouteImport
      parentRoute: typeof TabsRouteRoute
    }
  }
}

interface TabsRouteRouteChildren {
  TabsExploreRoute: typeof TabsExploreRoute
  TabsHistoryRoute: typeof TabsHistoryRoute
}

const TabsRouteRouteChildren: TabsRouteRouteChildren = {
  TabsExploreRoute: TabsExploreRoute,
  TabsHistoryRoute: TabsHistoryRoute,
}

const TabsRouteRouteWithChildren = TabsRouteRoute._addFileChildren(
  TabsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRouteRoute: TabsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
