/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TabsRouteRouteImport } from './routes/_tabs/route'
import { Route as TabsHomeRouteImport } from './routes/_tabs/home'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRouteRoute = TabsRouteRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsHomeRoute = TabsHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => TabsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof TabsHomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof TabsHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabs': typeof TabsRouteRouteWithChildren
  '/_tabs/home': typeof TabsHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home'
  id: '__root__' | '/' | '/_tabs' | '/_tabs/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRouteRoute: typeof TabsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/home': {
      id: '/_tabs/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof TabsHomeRouteImport
      parentRoute: typeof TabsRouteRoute
    }
  }
}

interface TabsRouteRouteChildren {
  TabsHomeRoute: typeof TabsHomeRoute
}

const TabsRouteRouteChildren: TabsRouteRouteChildren = {
  TabsHomeRoute: TabsHomeRoute,
}

const TabsRouteRouteWithChildren = TabsRouteRoute._addFileChildren(
  TabsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRouteRoute: TabsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
